incremental: false
lsi: false
safe: true
highlighter: rouge
theme: just-the-docs
url: https://esdmr.github.io/github-actions-test/

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
