name: Github Pages

on:
  push:
    branches:
      - master
      - releases/**

env:
  GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
  GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  JOB_NODE_VERSION: 16.x
  JOB_PNPM_VERSION: "6.9.0"
  JOB_RUBY_VERSION: "2.7"
  JOB_DOCS_BRANCH: docs
  JOB_COMMIT_MESSAGE: |-
    ${{ github.event.head_commit.message }}

    Original-commit: ${{ github.event.head_commit.url }}

defaults:
  run:
    shell: bash

jobs:
  update-docs:
    name: Update Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source

      # TODO: Build docs somehow to build/docs

      - name: Copy README to docs
        working-directory: source
        run: |-
          echo '---
          nav_order: 1
          ---' > build/docs/index.md
          cat README.md >> build/docs/index.md

      - name: Create branch ${{ env.JOB_DOCS_BRANCH }} if non-existent
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.JOB_DOCS_BRANCH }}

      - name: Checkout branch ${{ env.JOB_DOCS_BRANCH }}
        uses: actions/checkout@v2
        with:
          ref: ${{ env.JOB_DOCS_BRANCH }}
          path: docs

      - name: Copy folders to the docs branch
        run: |-
          rm -vrf docs/${GITHUB_REF#refs/heads/}/
          mkdir -vp docs/${GITHUB_REF#refs/heads/}/
          mv -vt docs/${GITHUB_REF#refs/heads/} source/build/docs/*

      - name: Configure git committer
        run: |-
          git config --global user.name user.name "$GIT_COMMITTER_NAME"
          git config --global user.email user.name "$GIT_COMMITTER_EMAIL"

      - name: Commit changes
        working-directory: docs
        run: |-
          git add --all .
          git commit --author "$GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>" \
            --message "$JOB_COMMIT_MESSAGE"

      - name: Push changes
        working-directory: docs
        run: git push origin $JOB_DOCS_BRANCH

  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs: update-docs
    if: success()

    steps:
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2.2.0
        with:
          pages_threshold: major_outage

      - name: Checkout branch master
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Checkout branch ${{ env.JOB_DOCS_BRANCH }}
        uses: actions/checkout@v2
        with:
          ref: ${{ env.JOB_DOCS_BRANCH }}
          path: docs

      - name: Copy template to docs
        run: cp -vr master/.github/pages-template/* docs

      - name: Use Node.js ${{ env.JOB_NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.JOB_NODE_VERSION }}

      - name: Use PNPM ${{ env.JOB_PNPM_VERSION }}
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.JOB_PNPM_VERSION }}

      - name: Set PNPM StoreDir
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Cache PNPM modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-

      - name: Install libraries
        working-directory: docs
        run: |-
          function copy_lib {
            mkdir -vp lib/$1
            cp -vr _lib/node_modules/$1/$2 lib/$1/$2
            echo Copied $1/$2
          }

          echo "::group::pnpm install"
          cd _lib
          pnpm install
          cd ..
          echo "::endgroup::"
          copy_lib katex LICENSE
          copy_lib katex/dist fonts
          copy_lib katex/dist katex.min.css
          copy_lib katex/dist katex.min.js
          copy_lib katex/dist/contrib auto-render.min.js
          rm -r _lib

      - name: Setup Ruby ${{ env.JOB_RUBY_VERSION }}
        uses: ruby/setup-ruby@v1.77.0
        with:
          working-directory: docs
          ruby-version: ${{ env.JOB_RUBY_VERSION }}
          bundler: Gemfile.lock
          bundler-cache: true

      - name: Build just-the-docs Search Data
        working-directory: docs
        run: bundle exec just-the-docs rake search:init

      - name: Build jekyll
        working-directory: docs
        run: bundler exec jekyll build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: docs/_site
          committer: ${{ env.GIT_COMMITTER_NAME }} <${{ env.GIT_COMMITTER_EMAIL }}>
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          jekyll: false
          commit_message: ${{ env.JOB_COMMIT_MESSAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
