name: Documentation
concurrency: docs

on:
  push:
    branches:
      - master
      - releases/**

env:
  GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
  GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  JOB_NODE_VERSION: 16.x
  JOB_PNPM_VERSION: "6.10.0"
  JOB_RUBY_VERSION: "2.7"
  JOB_DOCS_BRANCH: docs
  JOB_COMMIT_ORIGINAL_ID: ${{ github.event.head_commit.id }}
  JOB_COMMIT_ORIGINAL_URL: ${{ github.event.head_commit.url }}
  JOB_REPO_URL: https://github.com/${{ github.repository }}
  JOB_COMMIT_MESSAGE: |-
    ${{ github.event.head_commit.message }}

    Original-commit: ${{ github.event.head_commit.url }}

defaults:
  run:
    shell: fish {0}

jobs:
  update:
    name: Update documentation
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Install fish
        uses: fish-actions/install-fish@v1.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.JOB_NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.JOB_PNPM_VERSION }}

      - name: Setup pnpm store-dir
        run: pnpm config set store-dir ~/.pnpm-store/source/

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store/source/
          key: ${{ runner.OS }}-pnpm-source-${{ hashFiles('source/pnpm-lock.yaml') }}

      # Checkout
      - name: Create documentation branch if non-existent
        uses: esdmr/action-create-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.JOB_DOCS_BRANCH }}
          orphan: true

      - name: Checkout to master
        run: git clone $JOB_REPO_URL master

      # build
      - name: Build
        run: source master/.github/scripts/docs/update.fish

      # Deploy
      - name: Check for a concurrenct workflow
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          cancel_others: true
          skip_after_successful_duplicate: false
          concurrent_skipping: outdated_runs

      - name: Check GitHub Pages status
        if: success() && steps.skip_check.outputs.should_skip != 'true'
        uses: crazy-max/ghaction-github-status@v2.2.0
        with:
          pages_threshold: major_outage

      - name: Setup pnpm configuration for template libraries
        run: pnpm config set store-dir ~/.pnpm-store/docs/

      - name: Cache pnpm modules for template libraries
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store/docs/
          key: ${{ runner.OS }}-pnpm-docs-${{ hashFiles('master/.github/pages-template/**/pnpm-lock.yaml') }}

      - name: Setup deployment
        if: success() && steps.skip_check.outputs.should_skip != 'true'
        run: source master/.github/scripts/docs/predeploy.fish

      - name: Setup Ruby
        if: success() && steps.skip_check.outputs.should_skip != 'true'
        uses: ruby/setup-ruby@v1.77.0
        with:
          working-directory: docs
          ruby-version: ${{ env.JOB_RUBY_VERSION }}
          bundler: Gemfile.lock
          bundler-cache: true

      - name: Deploy
        if: success() && steps.skip_check.outputs.should_skip != 'true'
        run: source master/.github/scripts/docs/deploy.fish

      - name: Deploy to GitHub Pages
        if: success() && steps.skip_check.outputs.should_skip != 'true'
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: docs/_site
          committer: ${{ env.GIT_COMMITTER_NAME }} <${{ env.GIT_COMMITTER_EMAIL }}>
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          jekyll: false
          commit_message: ${{ env.JOB_COMMIT_MESSAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
