name: Test fish scripts

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: Path to executable script
        type: string
        required: true

jobs:
  test-fish:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - fishTag: 3.5.0
          #   fishFile: fish-3.5.0.tar.xz
          #   fishMajor: 3
          # - fishTag: 3.4.0
          #   fishFile: fish-3.4.0.tar.xz
          #   fishMajor: 3
          # - fishTag: 3.3.0
          #   fishFile: fish-3.3.0.tar.xz
          #   fishMajor: 3
          # - fishTag: 3.2.0
          #   fishFile: fish-3.2.0.tar.xz
          #   fishMajor: 3
          # - fishTag: 3.1.0
          #   fishFile: fish-3.1.0.tar.gz
          #   fishMajor: 3
          # - fishTag: 3.0.0
          #   fishFile: fish-3.0.0.tar.gz
          #   fishMajor: 3
          # - fishTag: 2.7.0
          #   fishFile: fish-2.7.0.tar.gz
          #   fishMajor: 2
          # - fishTag: 2.6.0
          #   fishFile: fish-2.6.0.tar.gz
          #   fishMajor: 2
          # - fishTag: 2.5.0
          #   fishFile: fish-2.5.0.tar.gz
          #   fishMajor: 2
          # - fishTag: 2.4.0
          #   fishFile: fish-2.4.0.tar.gz
          #   fishMajor: 2
          # - fishTag: 2.3.0
          #   fishFile: fish-2.3.0.tar.gz
          #   fishMajor: 2
          # - fishTag: 2.2.0
          #   fishFile: fish-2.2.0.tar.gz
          #   fishMajor: 2
          # - fishTag: 2.1.0
          #   fishFile: fish-2.1.0.tar.gz
          #   fishMajor: 2
          - fishTag: 2.0.0
            fishFile: fish-2.0.0.tar.gz
            fishMajor: 2

    runs-on: ubuntu-latest
    name: Fish ${{ matrix.fishTag }} (${{ matrix.fishFile }})

    steps:
      - name: Make installation directory
        run: |-
          mkdir .fish-bin
          echo "$(pwd)/.fish-bin" >> $GITHUB_PATH

      - name: Cache fish build
        uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d # tag=v3
        with:
          path: .fish-bin
          key: ${{ runner.OS }}-fish-${{ matrix.fishTag }}-${{ matrix.fishFile }}

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          path: .repo

      - name: Build fish
        run: bash .repo/build-fish.sh
        env:
          FISH_TAG: ${{ matrix.fishTag }}
          FISH_FILE: ${{ matrix.fishFile }}
          FISH_MAJOR: ${{ matrix.fishMajor }}

      - name: Test
        run: |-
          chmod +x .repo/fish-tests/${{ github.event.inputs.test_name }}
          ./.repo/fish-tests/${{ github.event.inputs.test_name }}
