name: Get runtime versions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: node .github/get-versions.js
        id: versions
      - run: echo Node.JS is ${{ steps.versions.outputs.node }}
      - run: echo PNPM is ${{ steps.versions.outputs.pnpm }}
      - run: corepack pnpm --version
      - run: corepack enable
      - run: which pnpm
      - run: pnpm --version
