name: Text Executable

on:
  workflow_dispatch:
    inputs:
      name:
        description: The executable to check for.
        required: true
        type: string

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: |-
          npm init -y
          npm i which
      - run: console.log(require('which').sync(process.env.EXEC_NAME))
        shell: cp {0} index.js
      - run: node index.js
        env:
          EXEC_NAME: ${{ github.event.inputs.name }}
